DROP TABLE IF EXISTS  `webbond_bbo`;
CREATE TABLE `webbond_bbo` (
  `bondKey` varchar(100) NOT NULL DEFAULT '',
  `listedMarket` varchar(10) NOT NULL DEFAULT '',
  `brokerId` varchar(10) NOT NULL DEFAULT '',
  `remaintTime` varchar(20) DEFAULT NULL,
  `bondCode` varchar(100) DEFAULT NULL,
  `shortName` varchar(200) DEFAULT NULL,
  `latestTransaction` varchar(100) DEFAULT NULL,
  `bidVolume` varchar(200) DEFAULT NULL,
  `bid` varchar(100) DEFAULT NULL,
  `bidBarginFlag` int(11) DEFAULT NULL,
  `ofr` varchar(100) DEFAULT NULL,
  `cdcValuation` varchar(100) DEFAULT NULL,
  `csiValuation` varchar(100) DEFAULT NULL,
  `issuerBondRating` varchar(20) DEFAULT NULL,
  `expection` varchar(20) DEFAULT NULL,
  `ratingInstitutionName` varchar(200) DEFAULT NULL,
  `bidSubCdc` varchar(100) DEFAULT NULL,
  `cdcSubOfr` varchar(100) DEFAULT NULL,
  `bidSubCsi` varchar(100) DEFAULT NULL,
  `csiSubOfr` varchar(100) DEFAULT NULL,
  `brokerName` varchar(100) DEFAULT NULL,
  `updateTime` varchar(20) DEFAULT NULL,
  `duration` varchar(100) DEFAULT NULL,
  `ofrBarginFlag` int(11) DEFAULT NULL,
  `ofrVolume` varchar(200) DEFAULT NULL,
  `bidPriceComment` varchar(200) DEFAULT NULL,
  `ofrPriceComment` varchar(200) DEFAULT NULL,
  `RemaintTimeValue` int(7) DEFAULT NULL,
  `latestTransactionValue` float(14,6) DEFAULT NULL,
  `bidVolumeValue` float(14,6) DEFAULT NULL,
  `ofrVolumeValue` float(14,6) DEFAULT NULL,
  `bidValue` float(14,6) DEFAULT NULL,
  `ofrValue` float(14,6) DEFAULT NULL,
  `cdcValuationValue` float(14,6) DEFAULT NULL,
  `csiValuationValue` float(14,6) DEFAULT NULL,
  `bidSubCdcValue` float(14,6) DEFAULT NULL,
  `bidSubCsiValue` float(14,6) DEFAULT NULL,
  `cdcSubOfrValue` float(14,6) DEFAULT NULL,
  `csiSubOfrValue` float(14,6) DEFAULT NULL,
  `updateDateTime` varchar(100) NOT NULL DEFAULT '',
  `createDateTime` varchar(100) DEFAULT NULL,
  `pinyinFull` varchar(1024) DEFAULT '',
  `ratingInstitutionPinyin` varchar(1024) DEFAULT '',
  `expectionValue` varchar(200) DEFAULT '',
  `bidVolumeSortValue` float(14,6) DEFAULT NULL,
  `ofrVolumeSortValue` float(14,6) DEFAULT NULL,
  `expectionSortValue` int(11) DEFAULT '0',
  `ofrQuoteIds` varchar(4096) DEFAULT NULL,
  `bidQuoteIds` varchar(4096) DEFAULT NULL,
  `bidRelationFlag` tinyint(4) DEFAULT NULL,
  `ofrRelationFlag` tinyint(4) DEFAULT NULL,
  `restSymbolDays` int(11) DEFAULT '0',
  PRIMARY KEY (`bondKey`,`listedMarket`,`brokerId`,`updateDateTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS  `webbond_trade`;
CREATE TABLE `webbond_trade` (
  `bondKey` varchar(100) NOT NULL DEFAULT '',
  `listedMarket` varchar(10) NOT NULL DEFAULT '',
  `tradeId` varchar(200) NOT NULL DEFAULT '',
  `brokerId` varchar(10) DEFAULT NULL,
  `brokerName` varchar(200) DEFAULT NULL,
  `dealType` varchar(20) DEFAULT NULL,
  `remaintTime` varchar(20) DEFAULT NULL,
  `bondCode` varchar(20) DEFAULT NULL,
  `shortName` varchar(200) DEFAULT NULL,
  `dealPrice` varchar(100) DEFAULT NULL,
  `cdcValuation` varchar(100) DEFAULT NULL,
  `csiValuation` varchar(100) DEFAULT NULL,
  `issuerBondRating` varchar(20) DEFAULT NULL,
  `expection` varchar(20) DEFAULT NULL,
  `ratingInstitutionName` varchar(200) DEFAULT NULL,
  `updateTime` varchar(20) DEFAULT NULL,
  `remaintTimeValue` int(7) DEFAULT NULL,
  `dealPriceValue` float(14,6) DEFAULT NULL,
  `cdcValuationValue` float(14,6) DEFAULT NULL,
  `csiValuationValue` float(14,6) DEFAULT NULL,
  `status` int(11) DEFAULT NULL COMMENT '0-normal, 2-referred',
  `dealStatus` int(11) DEFAULT NULL COMMENT '0-待单方确认, 1-待双方确认, 2-双方都已确认, 3-已完成 , 4-已作废 , 5-已取消',
  `updateDateTime` varchar(100) DEFAULT NULL,
  `createDateTime` varchar(100) DEFAULT NULL,
  `transType` varchar(100) DEFAULT 'update',
  `pinyinFull` varchar(1024) DEFAULT '',
  `ratingInstitutionPinyin` varchar(1024) DEFAULT '',
  `expectionValue` varchar(200) DEFAULT '',
  `expectionSortValue` int(11) DEFAULT '0',
  `restSymbolDays` int(11) DEFAULT '0',
  PRIMARY KEY (`bondKey`,`listedMarket`,`tradeId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;